Add files via upload
natty1978/SQL_Learning pull request #9
Opened 2023-10-15 13:30 UTC by natty1978

Домашка JOINS и пр.

2023-10-15 22:35 UTC, egornaumenko requested changes

2023-10-15 22:35 UTC, egornaumenko commented on HW.sql
> +     INNER JOIN
предыдущий тоже inner

2023-10-15 22:35 UTC, egornaumenko commented on HW.sql
> +  (salary + (salary * (`bonus_%` / 100))) AS total_salary
null бывает

2023-10-15 22:35 UTC, egornaumenko commented on HW.sql
> +GROUP BY
rollup

2023-10-16 12:39 UTC, natty1978 commented
---------------------------
# corrections
----------------------------

SELECT 
    c. client_name,
    q.amount,
    q.currency
FROM
    learning.`client` as c
   JOIN
        learning.`quotation` as q
    ON  c.client_id = q.client_id;
    
  ------------------------------------------
  # если  бонус  не внесен NULL
  ------------------------------------------
SELECT 
    master_name, 
    salary, 
    COALESCE(`bonus_%`, 0) AS bonus_percent,
    (salary + (salary * COALESCE(`bonus_%`, 0) / 100)) AS total_salary
FROM learning.masters;

  SELECT 
    master_name, 
    salary, 
    IFNULL(`bonus_%`, 0) AS bonus_percent,
    (salary + (salary * IFNULL(`bonus_%`, 0) / 100)) AS total_salary
FROM learning.masters;

------------------------------------------
  # если использовать ROLLUP
  ------------------------------------------
SELECT
    master_id, 
    master_name,
    SUM(salary) AS total_salary,
    SUM(salary * (`bonus_%` / 100)) AS total_bonus,
    SUM(salary) + SUM(salary * (`bonus_%` / 100)) AS total_income
FROM
    learning.masters
WHERE
    DATE_FORMAT(payment_date, '%Y') 
GROUP BY
    master_name
WITH ROLLUP;

2023-10-16 13:48 UTC, egornaumenko approved these changes

2023-10-18 13:07 UTC, merged